# Generated by Django 3.2.25 on 2024-07-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='Serial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
