# Generated by Django 3.2.25 on 2024-07-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_device_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='Serial',
            new_name='serial',
        ),
    ]
